# Generated by Django 5.0.7 on 2024-11-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homepage_desc", models.CharField(max_length=500)),
                ("homepage_button", models.CharField(max_length=250)),
                (
                    "homepage_img",
                    models.FileField(
                        default=None, max_length=500, null=True, upload_to="homepage"
                    ),
                ),
            ],
        ),
    ]
