# Generated by Django 5.0.7 on 2024-11-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_homepageright"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brandimg",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Brand_img",
                    models.FileField(
                        default=None, max_length=500, null=True, upload_to="Brandimg"
                    ),
                ),
            ],
        ),
    ]
