# Generated by Django 5.0.7 on 2024-11-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_brandimg"),
    ]

    operations = [
        migrations.CreateModel(
            name="featureproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=500)),
                (
                    "product_image",
                    models.FileField(default=None, max_length=500, upload_to="product"),
                ),
                ("product_price", models.DecimalField(decimal_places=3, max_digits=10)),
                ("product_rating", models.FloatField()),
                ("product_desc", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
