# Generated by Django 5.0.7 on 2024-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contactform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=500)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
    ]
